controller_manager:
  ros_parameters:
    update_rate: 30.0
    use sim_time: true # for gazebo simulation

  diff_cont: # name of the controller
    type: diff_drive_controller/DiffDriveController

  joint_broad:
    type: joint_state_broadcaster/JointStateBroadcaster

diff_cont: # parameters of controller
  ros_parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel names: [left_front_wheel_joint,left_back_wheel_joint]
    right_wheel names: [right_front_wheel_joint,right_back_wheel_joint]
    wheels_per_side: 2
    wheel_separation: 0.4 #  = base_width
    wheel_radius: 0.1 # = wheel_radius

    use_stamped_vel: false


# joint_state_broadcaster uses wheel encoder psoition to publish /joint_states msgs that robot_state_publisher 
# needs to generate wheel tf. for mobile robot not so important cause we look at pos of robot in space rather 
# than wheel pos. For ROBOT ARM much more importnat to have joint_state_broadcaster 

# joint_broad: 
#   ros_parameters:
#     publish_rate: 50.0
#     joint_names: [arm_base_forearm_joint,forearm_gripper_joint]

